### ISSUE TITLE
RFC: PHPStan extension API for $this variable in closures

### ISSUE THREAD

**Issue by ondrejmirtes** [larastan/larastan#1110]
Hi,
there are some issues like https://github.com/nunomaduro/larastan/issues/877 or https://github.com/nunomaduro/larastan/issues/166 that could be solved by Larastan properly understanding what is `$this` inside Closure passed to certain methods.

Can you tell me more about what the logic is? If I'd understand a few use-cases about this, I could design an API that Larastan could make use of to properly describe the behaviour.

Is this only about macros? What are they? Or are there multiple functionalities in Laravel that would take advantage of this?

**Comment by szepeviktor** [comment]
Hello Ondřej!

The most frequent one is binding a Closure it an object. In this Closure `$this` is the instance of `Collection`.

```php
        Collection::macro('isAssoc', function () {
            return Arr::isAssoc($this->toBase()->all());
        });
```

**Comment by ondrejmirtes** [comment]
Alright, two questions:

1) Where is the static `macro` method defined?
2) Can it be described like this? When there's a static call to `???::macro()`, the second argument is a closure, the `$this` inside the closure is `???`.

But I'm concerned about the declaring class of `macro` method, hope it's declared natively and not magically.

**Comment by szepeviktor** [comment]
1. In the framework https://github.com/laravel/framework/blob/d43075467da598edf6376af0589bb4c58b07a3dc/src/Illuminate/Macroable/Traits/Macroable.php#L19-L29
2. Yes!

**Comment by canvural** [comment]
Hi,

Thank you for considering this!

Yes, mainly this is about macros. But I think this could apply to any other code in PHP that uses `Closure::bindTo`

In Laravel you can see the implementation of macro [here.](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Macroable/Traits/Macroable.php) I guess the important parts are `macro`, `__call` and `__callStatic` methods. 

> When there's a static call to ???::macro(), the second argument is a closure, the $this inside the closure is ???.

Yes, that'd be correct.

**Comment by canvural** [comment]
The `Call to undefined method Foo:setBar` error is solved by this [extension.](https://github.com/nunomaduro/larastan/blob/master/src/Methods/Pipes/Macros.php) Basically we read the protected `macros` property with reflection. And get the closure. And create `ReflectionFunction` from it and use it for parameters, return type etc.

**Comment by ondrejmirtes** [comment]
Alright, I'll try to think of something but I won't rather promise any timeline as I can see some complications already:

1) the macro method is defined on a trait. "Declaring trait" is mostly hidden in PHPStan's Reflection APIs so you'd have to register the extension for all classes that implement the trait which isn't great.
2) The modern "no-code" approach would be to define some PHPDoc for this, something like `@param-closure-this self $macro`, but you can't use stub files for traits either, so that would have to be implemented first.

**Comment by canvural** [comment]
If it could be solved by a simple PHPDoc, I think it can be added to Laravel core. So no stub file would be needed.

**Comment by ondrejmirtes** [comment]
I wouldn't rely on that. If I implement this, I'd be glad if Larastan users could use it right away and not wait for Laravel's decision as they're pretty conservative about this - it took Laravel a few years to have generics for Collection and it probably wouldn't happen without Nuno being on the core team :)

**Comment by ondrejmirtes** [comment]
Support for `@param-closure-this` just landed in PHPStan 1.11.x-dev: https://github.com/phpstan/phpstan-src/commit/c8e1c8cbcbe502388d1cff237a9e1308cf837e89

PHPStan 1.11 is going to be released at some point in April or May, but you can already test this to see if it works for Laravel.

**Comment by canvural** [comment]
> Support for `@param-closure-this` just landed in PHPStan 1.11.x-dev: [phpstan/phpstan-src@c8e1c8c](https://github.com/phpstan/phpstan-src/commit/c8e1c8cbcbe502388d1cff237a9e1308cf837e89)
> 
> PHPStan 1.11 is going to be released at some point in April or May, but you can already test this to see if it works for Laravel.

Awesome! I'll test this and see where we can make use of it.

**Comment by rudiedirkx** [comment]
Is this in larastan now? Automatically for Laravel's Macroable?

**Comment by canvural** [comment]
> Is this in larastan now? Automatically for Laravel's Macroable?

Yes. But it's not released yet. I'll do it later this week.

**Comment by rudiedirkx** [comment]
> > Is this in larastan now? Automatically for Laravel's Macroable?
> 
> Yes. But it's not released yet. I'll do it later this week.

Still errors on protected methods, see #1252. Is that still a limitation of Phpstan?

**Comment by ondrejmirtes** [comment]
There's a feature request for rebinding scope: https://github.com/phpstan/phpstan/issues/11010
