### ISSUE TITLE
collection->pluck() for custom attributes shouldn't raise warning

### ISSUE THREAD

**Issue by vanyamil** [larastan/larastan#1188]
- Larastan Version: 2.1.2
- `--level` used: 6
- Pull request with failing test: don't know how

### Description

If your model has a custom attribute that **isn't** just modified by an accessor but creates a new one from other values, then you can't use pluck() on the Builder. You can only do it on the collection, once the models with at least the relevant attributes. As such, the warning should not be appearing when either of the parameters of the pluck() call is such an attribute.

### Laravel code where the issue was found

Assume you have a User model with first_name and last_name database columns. You then have a custom attribute:

```php
public function getFullNameAttribute(): string
{
  return $this->first_name . ' ' . $this->last_name;
}
```
(Equivalently, in Laravel 9 Attribute format:)
```php
public function fullName(): Attribute
{
  return Attribute::get(fn() => $this->first_name . ' ' . $this->last_name);
}
```

Then, having the line `User::get(['first_name', 'last_name'])->pluck('full_name')` succeeds but raises a Larastan warning "Called 'pluck' on Laravel collection, but could have been retrieved as a query.  ". But `User::pluck('full_name')` fails with 
`Illuminate\Database\QueryException with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'full_name' in 'field list' (SQL: select full_name from users)'`

**Comment by ap-coder** [comment]
I am also having this happen.

**Comment by neurotools** [comment]
I'm having same problem on a few projects, where I use calculated extra attributes on Models that can only be called with pluck on the collection of models, but not on the builder.

Example:
```
   // on App/Models/Page...

    /**
     * @return Attribute<string, null>
     */
    public function url(): Attribute
    {
        return Attribute::make(
            get: fn () => route('page', $this),
        );
    }
```
and the line tha raises the error in a Controller calls:
```
Pagina::publicado()->get()->pluck('title', 'url');
```
