### ISSUE TITLE
`HasOneOrMany` wrongly uses `TRelatedModel` as the type for the declaring model of the relation

### ISSUE THREAD

**Issue by nagmat84** [larastan/larastan#1284]
`HasOneOrMany` has only a single template parameter `TRelatedModel` which is bound to the model class which the relation points to. However, `HasOneOrMany` also uses `TRelatedModel` as the type for the model class which declares the relation.

https://github.com/nunomaduro/larastan/blob/ccdd599c464f9de6983a8d5e0f36daaf324b646f/stubs/HasOneOrMany.stub#L11-L20

The declaring model model (or parent or owning model) is not the same as the related model.

_Originally posted by @nagmat84 in https://github.com/nunomaduro/larastan/discussions/1275#discussioncomment-2933818_

**Comment by calebdw** [comment]
@canvural, @szepeviktor, this can now be closed
