### ISSUE TITLE
Inconsistent return types on model scopes with certain whereX functions when using static

### ISSUE THREAD

**Issue by jnoordsij** [larastan/larastan#1538]
- Larastan Version: 2.4.0
- `--level` used: 6
- ~~Pull request with failing test~~ Laravel example with failing result: https://github.com/jnoordsij/laravel-laravel/tree/model-scope-examples

### Description
On my abstract base model, I have implemented a few scopes that are shared between models that have columns with identical definitions. However, where for some of these scopes I can list the return type to be `Builder<static>` without issues, some of them will yield an error with some weird kind of nested `Builder`, e.g.
```
Method Sandbox\Model::scopeValid() should return
Illuminate\Database\Eloquent\Builder<static(Sandbox\Model)>
but returns
Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Builder<static(Sandbox\Model)>>>>.
```

When I use `self` instead of `static` the problem disappears, but this causes problems elsewhere, as I can not chain it with specific scopes or where clauses on the models implementing the abstract base model.

This might be partially solved by changing this
https://github.com/nunomaduro/larastan/blob/8982d3142c4b0de94c326f8f56212663b3e25b61/stubs/EloquentBuilder.stub#L235
to `@return static` (this is done on most other methods in this stub as well; I'm not entirely sure for what purpose).

### Laravel code where the issue was found

```php
<?php

namespace Sandbox;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model as BaseModel;
use Illuminate\Support\Carbon;

abstract class Model extends BaseModel
{
    /**
     * Scope for valid entries.
     *
     * @param  Builder<static>  $query
     * @return Builder<static>
     */
    public function scopeValid(Builder $query): Builder
    {
        return $query->whereDate('ValidUntil', '>=', Carbon::today())
                     ->orWhereNull('ValidUntil');
    }

    /**
     * Regular where scope.
     *
     * @param  Builder<static>  $query
     * @return Builder<static>
     */
    public function scopeTest(Builder $query): Builder
    {
        return $query->where('Column', true);
    }

    /**
     * Or null where scope.
     *
     * @param  Builder<static>  $query
     * @return Builder<static>
     */
    public function scopeTestOrNull(Builder $query): Builder
    {
        return $query->test()->orWhereNull('Column');
    }

    /**
     * Or null where scope.
     *
     * @param  Builder<static>  $query
     * @return Builder<static>
     */
    public function scopeTestWhereNull(Builder $query): Builder
    {
        return $query->whereNull('Column');
    }
}
```

See also https://github.com/jnoordsij/laravel-laravel/tree/model-scope-examples (run `composer install && ./vendor/bin/phpstan`).

**Comment by canvural** [comment]
Hi,

`static` type is really tricky thing to handle. I don't know how this nested builder type is constructed. Looks like it might be a bug.

But for your use case I'd suggest using generics. So you can add `@template T` to your `Model` class. And use `Builder<T>` instead of `Builder<static>` inside. That might work better.

**Comment by jnoordsij** [comment]
Yeah I figured it would probably be somewhat hard to solve, I was just a bit confused it worked perfectly fine on some methods (like regular `where`) but no on other like `orWhere` or `whereDate`. Like I mentioned above, it might have to do something with the stub files and some methods not being present there, but I'm not entirely sure on the handling of what's in there.

I've simply added an explicit ignore-error file for these particular errors now, so that works too. Hoping someone will manage to solve this one day; or maybe someday we'll even have generic builders in the Laravel source to solve this.

**Comment by calebdw** [comment]
@jnoordsij, can you test #1874 to see if that fixes your use case?

If it doesn't then this is definitely doable with the custom builder pattern so might consider switching to that over scopes

**Comment by calebdw** [comment]
I added this test that passed so I think this is fixed: https://github.com/larastan/larastan/pull/1874/commits/98b524b38134a4878e7bd6b0472439c381eb1606

**Comment by jnoordsij** [comment]
> @jnoordsij, can you test #1874 to see if that fixes your use case?
> 
> If it doesn't then this is definitely doable with the custom builder pattern so might consider switching to that over scopes

Just updated the example from the description to try out your fix, and can confirm it runs without any issues reported now!

**Comment by canvural** [comment]
Hi,

Like I explained in the PR associated, if there are no errors when analyzing the code that _calls_ these methods, then you can safely ignore these errors.
