### ISSUE TITLE
Macros registered as static methods using array syntax produce an internal error

### ISSUE THREAD

**Issue by jimbojsb** [larastan/larastan#1644]
- Larastan Version: 2.6.0
- `--level` used: whatever the default is
- Pull request with failing test:

### Description
`MacroMethodsClassReflectionExtension.php` - produces an internal error if a macro is registered to a static method, and that method is passed to the macro with array syntax. See [here](https://github.com/nunomaduro/larastan/blob/master/src/Methods/MacroMethodsClassReflectionExtension.php#LL123C25-L124C78)

The code assumes that if an array syntax is used, then the 0th element of the array will always be an instance. My workaround for this, which I prefer, is to use a splat instead and just not pass an array. 

### Laravel code where the issue was found

Does not work:
```php
class UrlGenerator
{
    public static function registerMacros()
    {
        \Illuminate\Routing\UrlGenerator::macro('testMacro', [__CLASS__, 'test']);
    }

    public static function test() {}
```
Works:
```php
class UrlGenerator
{
    public static function registerMacros()
    {
        \Illuminate\Routing\UrlGenerator::macro('testMacro', self::test(...));
    }

    public static function test() {}
```

**Comment by glennjacobs** [comment]
I am also seeing this with 

```php
use Illuminate\Support\Arr;

Arr::permutate($array);

```

**Comment by jimbojsb** [comment]
EDIT: That splat syntax comment doesn't actually work. It passes Larastan but it's a runtime error.
