### ISSUE TITLE
Query builder macros not detected

### ISSUE THREAD

**Issue by pxlrbt** [larastan/larastan#1675]
- Larastan Version: 2.6.3
- `--level` used: 5
- Pull request with failing test: 

### Description

It seems that Larastan doesn't detect query builder macros. It works fine if the macros are registered on EloquentQueryBuilder but not on the non-Eloquent one.

### Laravel code where the issue was found

```php
use Illuminate\Database\Query\Builder;

class AppServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        Builder::macro('test', function () {
            return $this;
        });
    }
}
```

```php
class TestController extends Controller
{
    public function test()
    {
        return User::query()->test()->get();
    }
}
```

### Error

`Call to an undefined static method App\Models\User::test()`

**Comment by canvural** [comment]
If you gonna use it on a model why would you register it on the normal builder?

**Comment by pxlrbt** [comment]
Updated the example: `return User::query()->test()->get();`

This is used in various places, models, relations, ...

**Comment by canvural** [comment]
`User::query() ` returns Eloquent builder. So still you can register it on Eloquent builder.

**Comment by pxlrbt** [comment]
That would fix Larastan issues. But I would need to register it on both, since we still need it on the normal query builder.

Is this the proposed solution? Duplicate registration because Larastan doesn't know, that Eloquent builder passes method calls to the query builder?

**Comment by canvural** [comment]
No, I'm just trying to understand what you are trying to achieve. 

Larastan definitely understands that Eloquent builder forwards method calls to the query builder. Just looks like there is a bug regarding the macros.

I'll keep it open. Maybe someone will contribute a fix. But personally I'd consider this an edge case, so I'll not be fixing it any time soon.

**Comment by keizah7** [comment]
I'm using `kalnoy/nestedset` package it has ``withDepth`` method
```php
$result = Category::withDepth()->find($id);

$depth = $result->depth;
```
Larastan:
```
Call to an undefined method Illuminate\Database\Eloquent\Builder<App\Models\Category>::withDepth().  
```

**Comment by calebdw** [comment]
@canvural, was this also fixed with 6e2729edb2ed97d1cfaecece59701f199177775c?

**Comment by canvural** [comment]
> @canvural, was this also fixed with [6e2729e](https://github.com/larastan/larastan/commit/6e2729edb2ed97d1cfaecece59701f199177775c)?

Oh, right. Good catch 👍🏽

**Comment by canvural** [comment]
Fixed with: https://github.com/larastan/larastan/commit/6e2729edb2ed97d1cfaecece59701f199177775c

**Comment by ghost** [comment]
> I'm using `kalnoy/nestedset` package it has `withDepth` method
> 
> ```
> $result = Category::withDepth()->find($id);
> 
> $depth = $result->depth;
> ```
> 
> Larastan:
> 
> ```
> Call to an undefined method Illuminate\Database\Eloquent\Builder<App\Models\Category>::withDepth().  
> ```

Hi @keizah7. What was your solution to this? Thanks!
