### ISSUE TITLE
Method Builder::whereX() should return static(Builder<Model>) but returns Builder<Model>

### ISSUE THREAD

**Issue by sanfair** [larastan/larastan#1676]
- Larastan Version: 2.6.3
- `--level` used: 5
- Pull request with failing test: https://github.com/sanfair/larastan-playground/pull/1

### Description

When defining a new `whereX` method in custom builder with return type annotation phpstan shows errors.

In PR you can find both possible definitions that correctly execute at runtime, but trigger errors on static analysis.

Real application example: https://github.com/koel/koel/blob/master/app/Builders/AlbumBuilder.php#L10-L13
Note: in this case, an error can be resolved by specifying the return type as `self`, but it is not always correct.

Possible related issues from phpstan: https://github.com/phpstan/phpstan/issues/5132 https://github.com/phpstan/phpstan/issues/4648
Note: solution with `self` used from these issues

### Code where the issue was found

```php
use Illuminate\Database\Eloquent\Builder as BaseBuilder;

/**
 * @template TModelClass of \Illuminate\Database\Eloquent\Model
 *
 * @extends BaseBuilder<TModelClass>
 */
abstract class Builder extends BaseBuilder
{
    public function whereSomething($column, $values, $boolean = 'and'): static
    {
        return $this->whereNotIn(...func_get_args());
    }

    public function whereSomethingElse($column, $values, $boolean = 'and'): self
    {
        return $this->whereNotIn(...func_get_args());
    }
}
```

----

I managed to find the exact place where the type is defined. I tried to replace `\PHPStan\Type\Generic\GenericObjectType` with `\PHPStan\Type\StaticType` but then it fails in other places.

https://github.com/nunomaduro/larastan/blob/706784ec6b1bad487692730dc20aeee0ff1b19fa/src/Methods/EloquentBuilderForwardsCallsExtension.php#L150-L154

**Comment by szepeviktor** [comment]
Hello!
Have you tries adding `@return TModelClass`?

**Comment by sanfair** [comment]
Hello, I may have made some confusion by stripping some information from the error just to fit in the title.

Here are the actual error messages:

```
 ------ ------------------------------------------------------------------- 
  Line   app/Models/Builder/Builder.php                                     
 ------ ------------------------------------------------------------------- 
  16     Method App\Models\Builder\Builder::whereSomething() should return  
         static(App\Models\Builder\Builder<TModelClass of                   
         Illuminate\Database\Eloquent\Model>) but returns                   
         App\Models\Builder\Builder<Illuminate\Database\Eloquent\Model>.    
 ------ ------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------- 
  Line   app/Models/Builder/UserBuilder.php                                  
 ------ -------------------------------------------------------------------- 
  14     Method App\Models\Builder\UserBuilder::whereSomethingElse() should  
         return App\Models\Builder\UserBuilder but returns                   
         App\Models\Builder\Builder.                                         
 ------ -------------------------------------------------------------------- 
```

You can check https://github.com/sanfair/larastan-playground/pull/1/checks for more context.

The problem is not in a model class. When phpstan analyzes method `Builder::whereSomething()` and sees the `static` keyword it expects that the return type will be `static(Builder)` but `$this->whereNotIn()` returns the `Builder` type without static.
Somehow larastan loses the proper type that should be inferred based on the definition from Laravel (see below)

I recreated the exact type structure but in raw PHP https://phpstan.org/r/bf3dd532-58f3-49c4-818e-fdf99883de72
But in Laravel + larastan inside the `Builder` class error will be on line 41, with the message as the error on line 49

Please check the types in the `test` method.

**Comment by szepeviktor** [comment]
> I recreated the exact type structure but in raw PHP

# 👍🏻

**Comment by canvural** [comment]
There were changes that might have fixed this in 2.x branch. Please test it and open a new issue if it still persists.
