### ISSUE TITLE
Detect usage of `env()` function outside from config folder

### ISSUE THREAD

**Issue by Seb33300** [larastan/larastan#1695]
Hello, 

In order to be able to use the `config:cache` command, we need to ensure that our project only use the `env()` function inside config files.
See related laravel documentation: https://laravel.com/docs/10.x/configuration#configuration-caching

Unfortunately, it seems that many developers are not aware about this and I can find usage of `env()` function in most of the projects I joined in the last few years.
I am looking for a solution to detect usage of `env()` outside of config files and make our CI to fail if that happens, so we can safely use the `config:cache` command during deployments.

I did not find any rule to detect that in Larastan and I was thinking that it could be a good feature to add.

**Comment by szepeviktor** [comment]
Very nice feature request!

PHP-CS-Fixer is not able to do that.
I use PHPCS: https://github.com/szepeviktor/running-laravel/blob/530dce9bb68f27e1b02d4cc41842e077051d43c5/phpcs.xml#L7-L77
