### ISSUE TITLE
Not recognizing models inheritance and toBase() return type after upgrading to Laravel 10

### ISSUE THREAD

**Issue by fabio-desimone** [larastan/larastan#1703]
- Larastan Version: 2.6.4
- `--level` used: 6
- Pull request with failing test:

### Description
After upgrading to Laravel 10, Larastan is not recognizing models and `toBase()` method return type properly.
It gives the error 
```
Parameter #1 $callback of method Illuminate\Database\Eloquent\Collection<(int|string),Illuminate\Database\Eloquent\Model>::map() expects 
 callable(Illuminate\Database\Eloquent\Model, int|string): App\Academy\Content\AcademyContent, 
 Closure(App\Academy\Content\Taxonomies\Models\AcademyContentTaxonomy): App\Academy\Content\AcademyContent given.
```

### Laravel code where the issue was found

```php
return $this->taxonomiesRepository->getDefaultTaxonomies($organisationId)
    ->toBase()
    ->map(function (AcademyContentTaxonomy $taxonomy) {
        return new AcademyContent(
            $taxonomy->taxonomy_id,
            strip_tags($taxonomy->title),
            AcademyContentType::TAXONOMIES,
            $taxonomy->language,
            );
    })
    ->toArray();
```

**Comment by szepeviktor** [comment]
Thank you for your report!!

So without `toBase()` PHPStan reports no problems.

**Comment by szepeviktor** [comment]
What if you add 2nd parameter?
`function (AcademyContentTaxonomy $taxonomy, $index) {`

**Comment by Fabio-DeSimone** [comment]
Already tried but I got the same exact error.
It is like it's not recognizing the `toBase()` return type since it complains about the Eloquent collection and not the Support collection
```
Parameter #1 $callback of method Illuminate\Database\Eloquent\Collection<(int|string)
```

and also seems it doesn't recognize the model inheritance, since `App\Academy\Content\Taxonomies\Models\AcademyContentTaxonomy` extends `Illuminate\Database\Eloquent\Model`.

I found a temporary fix regarding `toBase()` by using a temporary variable and giving the correct hint:
```php
/** @var Collection<AcademyContentArticleWithFlipCards> $articles */
$articles = $this->articleWithFlipCardsRepository
    ->getDefaultLanguageArticles($organisationId)
    ->toBase();

return $articles
    ->map(function (AcademyContentArticleWithFlipCards $articleWithFlipCards) {
        return new AcademyContent(
            $articleWithFlipCards->article_id,
            $articleWithFlipCards->plainTextTitle,
            AcademyContentType::ARTICLE_WITH_FLIP_CARDS,
            $articleWithFlipCards->language,
        );
    })
    ->toArray();
```
but I have 100 errors and I wouldn't go over all of them to fix them manually.

I also deleted the cache by using `vendor/bin/phpstan clear-result-cache` but it didn't solve it.

**Comment by Eugene-Melbourne** [comment]
I have the same problem on Laravel 9.52.14

it was working fine with phpstan/phpstan:1.10.9
but the problem started on phpstan/phpstan:1.10.10
now the latest available version(phpstan/phpstan:1.10.27) still has this problem

more details in the stackoverflow question 
https://stackoverflow.com/questions/76729231/larastan-complains-about-collection-methods-paramaters-after-upgrading-to-larave/76856109#76856109

**Comment by Eugene-Melbourne** [comment]
I created a bug report on phpstan, please contribute to the discussion there
https://github.com/phpstan/phpstan/issues/9735

**Comment by canvural** [comment]
Looks like the return type of `getDefaultTaxonomies` is wrong. If you fix it so that it returns a collection of `AcademyContentTaxonomy` your error would be solved.
