### ISSUE TITLE
LazyCollection flatMap returns wrong type

### ISSUE THREAD

**Issue by JosephSilber** [larastan/larastan#1704]
- Larastan Version: 2.6.4
- `--level` used: 3
- Pull request with failing test: [this repository](https://github.com/JosephSilber/larastan-regression/blob/c755e37db3596f2884390c0fd408337f077a5d77/app/Http/Controllers/Controller.php#L14-L19)

### Description

When using the `flatMap` method on a `LazyCollection`, it doesn't pick up the static type from `EnumeratesValues`. It returns `Illuminate\Support\Traits\EnumeratesValues<int, mixed>` instead of a `LazyCollection`.

![image](https://github.com/nunomaduro/larastan/assets/1403741/ab89eebb-d225-4cfc-9e99-b954d716314f)

### Laravel code where the issue was found

```php
use Illuminate\Support\LazyCollection;

function test(): LazyCollection
{
    return LazyCollection::times(5)->flatMap(function ($number) {
        return [$number];
    });
}
```

**Comment by calebdw** [comment]
Appears that this is working below Laravel 9.48 but is broken above that
