### ISSUE TITLE
Wrong return type when overwriting Request::user()

### ISSUE THREAD

**Issue by AJenbo** [larastan/larastan#1718]
- Larastan Version: 2.6.4
- `--level` used: 8

### Description
Larastan will overwrite the return type of requests that narrow the return of `user()`.
```
  5     Cannot access property $id on App\User|null.
```

### Laravel code where the issue was found

```php
<?php

namespace App\Http\Requests;

resolve(AuthedRequest::class)->user()->id
```

```php
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use App\User;

class AuthedRequest extends FormRequest
{
    public function authorize(): bool
    {
        return parent::user() instanceof User;
    }

    public function user($guard = null): User
    {
        $user = parent::user($guard);
        if (!$user instanceof User) {
            abort(403);
        }

        return $user;
    }
}
```

**Comment by szepeviktor** [comment]
I think Larastan does not know that `AuthedRequest` may not have an instance thus it is `null`.

**Comment by AJenbo** [comment]
Laravel (9) hints it as mixed via phpdoc. Larastan then deduces it down to ?User. But also overwrites children with a more narrow and native typehint which should not happen.

**Comment by sandeshjangam** [comment]
I am facing the same issue


Define the new request class overriding user method

```
namespace App\Http\Requests;

use App\Helpers\Response;
use App\Models\User;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Http\Request;

class TopRequest extends Request
{
    /**
     * Get the user or throws an exception.
     *
     * @param  string|null  $guard
     * @return User User model
     *
     * @throws HttpResponseException
     */
    public function user($guard = null)
    {
        $user = parent::user($guard);

        if (! $user instanceof User) {
            throw new HttpResponseException(
                Response::unauthorized(__('User doesn\'t exist'))
            );
        }

        return $user;
    }
}
```

Use the new request in the controller

```
class AbcController extends Controller
{
     /**
     * List
     *
     * @since x.x.x
     */
    public function index(TopRequest $request): JsonResponse
    {
        // Get logged in user.
        $user = $request->user();

        $email = $user->email
   }
}
```

Error
```
 :147   Cannot access property $email on App\Models\User|null. 
```

If I define new `getUser` method and use it instead of `user` it works perfecly fine. So issue is definilty lies in stan check. 

Any solution for this?

**Comment by sandeshjangam** [comment]
Hello @canvural 

I’ve been following this issue closely and would like to help expedite its resolution. Is there anything specific that needs to be addressed or tested to get this PR merged? I can assist with code reviews, testing, or any other necessary tasks.

**Comment by HDVinnie** [comment]
Any update?

**Comment by sandeshjangam** [comment]
> Hello @canvural
> 
> I’ve been following this issue closely and would like to help expedite its resolution. Is there anything specific that needs to be addressed or tested to get this PR merged? I can assist with code reviews, testing, or any other necessary tasks.

Any update?

**Comment by AJenbo** [comment]
> Any update?

Doesn't look like it.

> to get this PR merged

It's an issue, not a PR

**Comment by ProteanCode** [comment]
I had an issue with `$request->user()` but adding `orchestra/testbench` helped to resolve it
