### ISSUE TITLE
Unable to resolve the template type TFlatMapKey in call to method

### ISSUE THREAD

**Issue by hmingv** [larastan/larastan#1721]
- Larastan Version: 2.6.4
- `--level` used: 9

### Description
I don't quite know how to set the type of TFlatMapKey and TFlatMapValue, this question makes me very confused.

![image](https://github.com/nunomaduro/larastan/assets/57735185/ade075ce-dcad-4e9f-a317-496ae7df8c84)

The type of the roles attribute is already declared.

![image](https://github.com/nunomaduro/larastan/assets/57735185/bbc7eb4b-cdda-4ca6-b0e7-aebf786fd35e)
![image](https://github.com/nunomaduro/larastan/assets/57735185/1e512523-b144-4994-b2d0-0b1fe0776fca)

How should I avoid this error?

**Comment by mad-briller** [comment]
the flat map key and flat map value are the results of the closure, not whats passed in, so whatever the result of `->get()` is, is not accurately typed enough

the `@phpstan-ignore-next-line` will probably be hiding your real issue

**Comment by calebdw** [comment]
Can this be closed?
