### ISSUE TITLE
UnusedViewsRule does not pass an existing file path to RuleErrorBuilder

### ISSUE THREAD

**Issue by ondrejmirtes** [larastan/larastan#1725]
- Larastan Version: b49b6d3ec144c675fa86bbe453ef11d8c42c2016

### Description

The next version of PHPStan is going to require an existing file path to be passed to `RuleErrorBuilder::file()`. This prevents various issues with the baseline and result cache.

When I try this, Larastan test suite fails with:

```
1) Rules\UnusedViewsRuleTest::testRule
PHPStan\ShouldNotHappenException: File unused.blade.php does not exist.

phar:///Users/ondrej/Development/larastan/vendor/phpstan/phpstan/phpstan.phar/src/Rules/RuleErrorBuilder.php:56
/Users/ondrej/Development/larastan/src/Rules/UnusedViewsRule.php:75
phar:///Users/ondrej/Development/larastan/vendor/phpstan/phpstan/phpstan.phar/src/Testing/RuleTestCase.php:126
phar:///Users/ondrej/Development/larastan/vendor/phpstan/phpstan/phpstan.phar/src/Testing/RuleTestCase.php:86
/Users/ondrej/Development/larastan/tests/Rules/UnusedViewsRuleTest.php:50
```

That's because `$unusedViews` in UnusedViewsRule contains strings like `unused` and not paths to existing files.

**Comment by mad-briller** [comment]
@ondrejmirtes does the path contained in `RuleErrorBuilder::file()` have to be one that was analyzed?

For a bit of context this rule is a bit strange as it's a collector / rule pair, where the collector finds all used view names and that is compared against all known view files to find the list of unused. As a result the `unused.blade.php` file is not actually analyzed.

**Comment by ondrejmirtes** [comment]
Doesn't have to be analysed, but it has to be an existing absolute filepath on disk.

**Comment by mad-briller** [comment]
sweet, thanks for that, i'll get this resolved
