### ISSUE TITLE
Eloquent\Collection map() returns Eloquent\Collection, gets typed as Support\Collection

### ISSUE THREAD

**Issue by Grldk** [larastan/larastan#1731]
- Laravel Version: 10.15.0
- Larastan Version: 2.6.3
- `--level` used: 6

### Description

Code looks like this:

```php
use Illuminate\Database\Eloquent\Collection as EloquentCollection;

        if ($collection instanceof EloquentCollection) {
            \PHPStan\dumpType($collection);

            $collection = $collection
                ->map(fn (User $user) => $user)
            ;

            \PHPStan\dumpType($collection);
        }
```
Dumped type before map: Illuminate\Database\Eloquent\Collection<int, App\Models\User>
Dumped type after map: Illuminate\Support\Collection<int, App\Models\User>

Expected type after map: Illuminate\Database\Eloquent\Collection<int, App\Models\User>

The type hint of the map function in Eloquent\Collection is `@return \Illuminate\Support\Collection<TKey, TMapValue>|static<TKey, TMapValue>`, so I'm thinking this is caused by Larastan?

**Comment by Grldk** [comment]
But wouldn't the `static<TKey, TMapValue>` part of the docblock result in a `Illuminate\Support\Collection<int, App\Models\User>|Illuminate\Database\Eloquent\Collection<int, App\Models\User>` type after the map function? 

Or is this a phpstan bug?

**Comment by szepeviktor** [comment]
I think this is the relevant code in Larastan.

https://github.com/nunomaduro/larastan/blob/17300755ef7f5a0cd520118bf872d992d4453c26/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php#L86-L95

**Comment by Grldk** [comment]
I am not really versed enough in phpstan/larastan to understand that code.. But the scenario we're talking about here is not covered by those tests..
