### ISSUE TITLE
`HasManyThrough::cursor` returns a generator

### ISSUE THREAD

**Issue by szepeviktor** [larastan/larastan#839]
```php
    /**
     * Get a generator for the given query.
     *
     * @return \Generator
     */
    public function cursor()
    {
        return $this->prepareQueryBuilder()->cursor();
    }
```

PHPStan https://phpstan.org/blog/generics-in-php-using-phpdocs tells us to use generics: `Generator<TKey, TValue, TSend, TReturn>`

`$this->category->quizzes()->cursor()->reduce(...` produces `Call to an undefined method Generator::reduce().`

What return type should we declare?

**Comment by canvural** [comment]
What is the real return type if you do something like `dd($this->category->quizzes()->cursor()`? Should be `\Illuminate\Support\LazyCollection` I guess?

**Comment by szepeviktor** [comment]
Yes `LazyCollection`.

**Comment by canvural** [comment]
Looks like for Laravel 6 it was generator. But when lazy collections is introduced, return type became `LazyCollection`

We can modify the stub so that it returns `LazyCollection` But that would break Laravel 6 compatibility I think. So right now, I don't have a good solution for this 😕

**Comment by szepeviktor** [comment]
What is Laravel 6??

:)

**Comment by calebdw** [comment]
Can this be closed? It seems stale: `HasManyThrough::cursor` returns a LazyCollection
